export { default as HomePage } from "./HomePage";
export { default as AboutPage } from "./AboutPage";
export { default as ContactUsPage } from "./ContactUsPage";
export { default as LeadPage } from "./LeadPage";
export { default as BituahHovaPage } from "./BituachHovaPage";
export { default as BituahZadGimelPage } from "./BituahZadGimelPage";
export { default as BituahMakifPage } from "./BituahMakifPage";
export { default as BituahDiraPage } from "./BituahDiraPage";
export { default as NotFoundPage } from "./NotFoundPage";
